import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import Script from "next/script";

import Navbar from "../components/navbar"
import Footer from "../components/footer"

export const metadata = {
  title: "AMAM Fashion | Fashion Products E-Commerce Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
